USE logans_books;

-- Drop Tables
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Contribution;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS AuthorPhoto;
DROP TABLE IF EXISTS Series;
DROP TABLE IF EXISTS PublisherLocation;
DROP TABLE IF EXISTS Language;
DROP TABLE IF EXISTS Publisher;

DROP TABLE IF EXISTS BookCategoryDetail;
DROP TABLE IF EXISTS BookContributionDetail;
DROP TABLE IF EXISTS AuthorCategoryDetail;
DROP TABLE IF EXISTS BookAuthorDetail;
DROP TABLE IF EXISTS BookSeriesDetail;
DROP TABLE IF EXISTS PublisherLocationDetail;
DROP TABLE IF EXISTS BookLanguageDetail;
DROP TABLE IF EXISTS BookPublisherDetail;

DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS State;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Residence;

DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS AccessLevel;

DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Bookshelf;
DROP TABLE IF EXISTS BookshelfBookDetail;

DROP TABLE IF EXISTS OpenlibBookEndpoints;
DROP TABLE IF EXISTS GoogleBookEndpoints;

DROP TABLE IF EXISTS Pagination;
